apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: parakeet-nim-pvc
  namespace: nvidia-nim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llama-nim-pvc
  namespace: nvidia-nim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
